image: jangrewe/gitlab-ci-android

variables:
  BUILD_APPS: "antitheftprotector calculator rollingdice"

before_script:
  - mkdir outputs


#   - export GRADLE_USER_HOME=$(pwd)/RollingDice/.gradle
#   - chmod +x ./RollingDice/gradlew

# cache:
#   key: ${CI_PROJECT_ID}
#   paths:
#     - .gradle/

stages:
  - build
  - test
  - release
  - deploy

# master #######################################################################
lintDebug:
  stage: build
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
        cd ..
      done
  only:
    refs:
      - master

assembleDebug:
  stage: build
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        ./gradlew assembleDebug
        cd ..
      done
  only:
    refs:
      - master

testDebug:
  stage: test
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        ./gradlew -Pci --console=plain :app:testDebug
        cd ..
      done
  only:
    refs:
      - master

assembleRelease:
  stage: release
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        echo $KEYSTORE_FILE | base64 -d > my.keystore
        ./gradlew assembleRelease
        mv ./app/build/outputs/apk/release/app-release-unsigned.apk ../outputs/$FOLDER.apk
        cd ..
      done

  only:
    refs:
      - master
  artifacts:
    paths:
      - ./outputs
      # - ./$CI_COMMIT_REF_NAME/app/build/outputs/apk/release/
    # - CHANGELOG

    expire_in: 1 week



# app branches #################################################################
# lintDebugApp:
#   stage: build
#   script:
#     - cd $CI_COMMIT_REF_NAME
#     - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
#   except:
#     refs:
#       - master
#
# assembleDebugApp:
#   stage: build
#   script:
#     - cd $CI_COMMIT_REF_NAME
#     - ./gradlew assembleDebug
#   except:
#     refs:
#       - master
#
# testDebugApp:
#   stage: test
#   script:
#     - cd $CI_COMMIT_REF_NAME
#     - ./gradlew -Pci --console=plain :app:testDebug
#   except:
#     refs:
#       - master

assembleReleaseApp:
  stage: release
  script:
    - export KEYSTORE_FILE="MIIKOwIBAzCCCfQGCSqGSIb3DQEHAaCCCeUEggnhMIIJ3TCCBYEGCSqGSIb3DQEHAaCCBXIEggVuMIIFajCCBWYGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBSGteln2vqZsY+Nv/dxXxeLKy1XGQIDAMNQBIIEyKhc7z9ZIfLrEDeTspm2Xok87sg93Kob9wjm9MxgdHmVFiIbyJGAEBLVDwUmHgCd3K1GX/wHCz2Qi4j8dc1aPieXpv2qz0wsEyb0tseB549K4bT6ylCCkYRjVMHg5FFuj4hG6IZFoz4yy09mh/slTruftG/bESB2GMZubbN1h0wE85m4plBdw/UsmLwAB00KUG9iin5pSTHcULqESq1j/xJd1rTLPjvLPh3Ed08fs+BLaN5bSJ4hRK3H6ugsdQxWpSoUo4MvCEG7lFz+iPDylL7tBxffMAaM2BZf1/JKnLnDgurtHr5hF5krwZqLuSp8IbaDfDZpip+Aa3jJco1eOXp3KChiIRCt3Ypb96ti2Bd37GXDqbGNf1sabD8rHsUcbUVahlByXdJb77PMbOVaCFZ+ysuwPaztMet22gP7dj9EOtBnHfz1rmw2AwNek5galYjvaN0EWn9/JlV+Nn10+td9qBA8bF/YK9Gc6Zuss4zJfF0SU4ELZwhebbFhgu8KozzSjTJhJl5SLGa0fjqiE5MvEasRdRnzQyKhaHvyVEWWrshaJL0J5PeduAfN/iUrDv19X5YdQd95jeNhDvVq4GTA0R67IIc6W9wWARWx56UMzvIh0WvC4sQNuglWdLZlGZMS5lcfszRDPdoEuuyqBsRUpUtPw76T/GmuM9pMwIteSvhHrqD3tJQ13MXv9H8RSst3N5vLRkiDZmE8x97T+6gNPvA5Wa2t02XdY6ZTlc6QsgI3++FKOHeijrkuOAypuj7fpPMmvxzdpwXwlzHANhMSMTPq3X/48GUIGlA/5lRVytlto+7Mx9ue8Vvy3tZuod1c255ga0cxGmAv9StGNVE5cj9ArRFUbe/5Ej1FdemdqUpqHgsUjip5UUUlmWvrL+VjwvKVbCQm0NyUFikmh/ufA9ePUXDB5Bf5Qq8K/Bz8c36tg7a8FU8M02fxAk4GYKTtRDE37gQG3VU4WHH7ZCaBPKCA0sFjvTzpnpfLrJhImds1rU+/K8z7PSuhCZHuMCUf1d4cFMBc1/RVvpkvacB0RsLCLT9lgcOGkzsXnxYuY775iaTU5jliYp7N5++24tIXGScwr/R+jnfmCD8fcpEdItQ7EI34XMOS4gNKBHvVdoQ87IL0ua7kVJsYAmecCJxsYTmoLUuJCafHmNE2g9vL9Wg5lVV8s9HTLOh0ksp1jOu95kEYFnaKO1y2aaLlytCt/DZ2O8Mvf0OUfB2x0yHrEM/IzyS2cGLZLCpQpzY7uo1pa/z7YOoMrw8I2sF4JAn815ubpzp1YLnGqChWaffhS+VvaJ/t/xkZ2yEHk/7w5encI3ixO7BAbyQgQ1dv2swMVMvun3wRsS3NnaP1pirNwGqPUVigFWEDjjCmOSjwYi40MF70wbhdCd35qGIjI3FnCLnVQ2lj1/mNyCNM/YYyswD85tH7Lq/MdcngiSFMErlnR+/kCIAZhiUZN1D/hgSlk/sfuI4tHWXl4q47qD0U2hUPNo1QQ/kZUDab3BTG0tIgH5tWFbRfciQuTaTPR8WwnUiyCFqHTaD/t8A72aUhibvsLlDpinCja66ByoSFKJa0VqZUjiPJA66Co50cnu9E+WWi/4i5DlGUoNXCcf0GnVy1QWriKTFYMDMGCSqGSIb3DQEJFDEmHiQAYQBuAHQAaQB0AGgAZQBmAHQAcAByAG8AdABlAGMAdABvAHIwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTU3ODYzNjYxNzc4OTCCBFQGCSqGSIb3DQEHBqCCBEUwggRBAgEAMIIEOgYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQU9SRxw44OQFZHI/5xjcPJxKkKxNwCAwDDUICCBACltxRsWYRx2jZRYYUc9+e2K8sP8JAsx/ugdeNx8ccuG5MLQnsXAEzVYuUjEHrpIgDre12HUCeIbFM2R/qS55xKqyXrzL0scKLXDILI8EOGxIgxqbG9WWDwJ8qk9ejrzH2PCtuG9PgO3Vbtdb1fb7DVQiXhgI+k2jx3tCEZ0mjkHhTEky2pNgbk3KwqMXDvqEcErtt5UHLVwJKAtebpM9Hpk8ljHDHAErYek2d4KcpajYx8w6gBbJNB4pjLzHEWnAgOBL73obDAv0gTMT4Rzi/61HQqDqmXUKKSlR9bMLpIfOUlF9+Y7LFxQkrOeFiuxwyt/bWptPycFTYF21ssGUVRyFr7grq+f23WvHVNPH/Xv8g82MhFvEJFTgetSPZPA/fQ6fNxWqQPtUP0pAj+gfaqd21wLaWovJiTEw1ft+kpuZMmGrOu5wMI5rKOdrElMl11wDB8ZrGFukxr10bidwU0gHBPcOMDU/Zzqm33hJ5+/P4T9vIwMUM+LraZoUPdedj0Q3tg/tcyb0qe5jfcoTUFGQ3csSTWIBcddCEqwP28rziS9OGUkOcxPLANR5Lyk1151ZfutBuFaxH/7Kvvbi4ciARRIIovh5dxG6n+5dLhfOtCY4SWmi6h6Dp3WeoPOkuv/KNGy76jlUhbGHbwR5IrUq+B8krAqoZ3SnDnvFImIH5QGF6MKS++rmr4jjcKZf2jEaVJGF1lvyYDNrO4pGupIfMFEbcqefy3GyghfHLiHx89xggSLXeKCJOUUX6UEAm+OgcySS9UUzhdN9aGDrT7B4Yf5r2GwcUDQB47WDjcbjVntWWOmFdbf7WrqI5jMPs6tFeyFSAplluDxoV/CNUjrgYOMTLvVvfImCGh0RW5OPeNDNb7ruRXphIqWQig64DEAFOpeDl92+R3W3jA9MnMukJqLkXUts+jt7dloHFeF2jU+FDABuc0mKI5E7wJmhzOseUNOyq0mA7pZx4sqsNEjvkIK+7qk+bXOUNE7NiJIqJh1ub1COSUTlG4Sr1WXKbDAHTaL6SeOX5pMt/7nJ1N2xNe4ZSONwrOgU+MythKMw1aj56c8K4j3P36I/AZcQDxKUgS54u12Jmd8msLbLNYPP9fpYDEGXEcFAYs/ImVvoOqXFllUfXqmkM+0B+W4mHHtCql0kTiBLZo8mN80FnIGzukjbjCbS2LPGatN11+wmAYgB1AGfezEY1UfApATQDhVWFNLk5UpZH87dDxh/u/7sk8U3vt5gO6SpmOvzhQ6gPt4lFFIqLzxQt8L/9N53phQHHjBJaPrnwNErXIcdU8v82u1BRWnd/N+u9yXUkgq516e/iZg3Raz2EYLuo7Ce2DgaO2lHmmQSpshYwd1HI0MD4wITAJBgUrDgMCGgUABBSIpOsFVcXKJoSJbk9mVsApVgRtlwQUTn6/CDV9skuTtqpO9u2dtEUVqEMCAwGGoA=="
    - export KEYSTORE_PASSWORD='devFromaXe2$ome1'
    - export antitheftprotector='atp@maxeoneo'
    - cd $CI_COMMIT_REF_NAME
    - eval "PASSWORD=\"\$$CI_COMMIT_REF_NAME\""
    - echo $KEYSTORE_FILE > key.txt
    - cat key.txt | base64 -d > my.keystore
    - cat my.keystore
    - echo $PASSWORD
    - echo $KEYSTORE_PASSWORD
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$CI_COMMIT_REF_NAME
      -Pandroid.injected.signing.key.password=$PASSWORD

    - mv ./app/build/outputs/apk/release/app-release.apk ../outputs/$CI_COMMIT_REF_NAME.apk
  except:
    refs:
      - master
  artifacts:
    paths:
      # - ./
      - ./$CI_COMMIT_REF_NAME/app/build/outputs/apk/release/
    # - CHANGELOG

    expire_in: 1 week
