stages:
  - build
  - test
  
build:
  stage: build
  script:
    - echo "Building"
    - mkdir output
    - cd GradleTest
    - ./gradlew assemble
    - cd ../output
    - mv GradleTest/app/build/outputs/apk/debug/app-debug.apk ./GradleTest-debug.apk
  artifacts:
    paths:
      - output/

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "output/GradleTest-debug.apk"
