image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/Calculator/.gradle
  - chmod +x ./Calculator/gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - test
  - release
  - deploy

lintDebug:
  stage: build
  script:
    - cd Calculator
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - cd Calculator
    - ./gradlew assembleDebug

testDebug:
  stage: test
  script:
    - cd Calculator
    - ./gradlew -Pci --console=plain :app:testDebug

assembleRelease:
  stage: release
  script:
    - cd Calculator
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      # -Pandroid.injected.signing.key.password=$KEY_PASSWORD
  artifacts:
    paths:
    - app/build/outputs/apk/release
    - CHANGELOG

# build:
#   stage: build
#   script:
#     - echo "Building"
#     - mkdir output
#     - cd Calculator
#     - ./gradlew assemble
#     - cd ../output
#     - mv ../Calculator/app/build/outputs/apk/debug/app-debug.apk ./Calculator-debug.apk
#   artifacts:
#     paths:
#       - output/
#
# test:
#   stage: test
#   script:
#     - echo "Testing"
#     - test -f "output/Calculator-debug.apk"
