image: jangrewe/gitlab-ci-android

variables:
  BUILD_APPS: "antitheftprotector calculator rollingdice"

before_script:
  - mkdir outputs


#   - export GRADLE_USER_HOME=$(pwd)/RollingDice/.gradle
#   - chmod +x ./RollingDice/gradlew

# cache:
#   key: ${CI_PROJECT_ID}
#   paths:
#     - .gradle/

stages:
  - build
  - test
  - release
  - deploy

# master #######################################################################
lintDebug:
  stage: build
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
        cd ..
      done
  only:
    refs:
      - master

assembleDebug:
  stage: build
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        ./gradlew assembleDebug
        cd ..
      done
  only:
    refs:
      - master

testDebug:
  stage: test
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        ./gradlew -Pci --console=plain :app:testDebug
        cd ..
      done
  only:
    refs:
      - master

assembleRelease:
  stage: release
  script:
    - >
      for FOLDER in $BUILD_APPS; do
        cd $FOLDER
        echo $KEYSTORE_FILE | base64 -d > my.keystore
        ./gradlew assembleRelease
        mv ./app/build/outputs/apk/release/app-release-unsigned.apk ../outputs/$FOLDER.apk
        cd ..
      done

  only:
    refs:
      - master
  artifacts:
    paths:
      - ./outputs
      # - ./$CI_COMMIT_REF_NAME/app/build/outputs/apk/release/
    # - CHANGELOG

    expire_in: 1 week



# app branches #################################################################
lintDebugApp:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  except:
    refs:
      - master

assembleDebugApp:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - ./gradlew assembleDebug
  except:
    refs:
      - master

testDebugApp:
  stage: test
  script:
    - cd $CI_COMMIT_REF_NAME
    - ./gradlew -Pci --console=plain :app:testDebug
  except:
    refs:
      - master

assembleReleaseApp:
  stage: release
  script:
    - echo $KEYSTORE_FILE
    - cd $CI_COMMIT_REF_NAME
    - eval "KEYPASS=\"\$$CI_COMMIT_REF_NAME\""
    - echo $KEYSTORE_FILE > key.txt
    - cat key.txt | base64 -d > my.keystore
    - ./gradlew assembleRelease
     # -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
     # -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
     # -Pandroid.injected.signing.key.alias=$CI_COMMIT_REF_NAME
     # -Pandroid.injected.signing.key.password=$KEYPASS
    - APP_PATH="./app/build/outputs/apk/release/app-release-unsigned.apk"

    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my.keystore -storepass $KEYSTORE_PASSWORD -keypass $KEYPASS $APP_PATH $CI_COMMIT_REF_NAME

    - SDK_VERSION=$(ls -t ${ANDROID_SDK_ROOT}/build-tools/ | head -n 1)
    - echo $SDK_VERSION
    - ${ANDROID_SDK_ROOT}/build-tools/${SDK_VERSION}/zipalign -p -f -v 4 $APP_PATH ../outputs/$CI_COMMIT_REF_NAME.apk

    # - mv $APP_PATH ../outputs/$CI_COMMIT_REF_NAME_unsigned.apk
  except:
    refs:
      - master
  artifacts:
    paths:
      # - ./
      # - ./$CI_COMMIT_REF_NAME/app/build/outputs/apk/release/
      - ../outputs
    # - CHANGELOG

    expire_in: 1 week
