image: jangrewe/gitlab-ci-android

before_script:
  - mkdir outputs
#   - export GRADLE_USER_HOME=$(pwd)/RollingDice/.gradle
#   - chmod +x ./RollingDice/gradlew

# cache:
#   key: ${CI_PROJECT_ID}
#   paths:
#     - .gradle/

stages:
  - build
  - test
  - release
  - deploy

lintDebug:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - ./gradlew assembleDebug

testDebug:
  stage: test
  script:
    - cd $CI_COMMIT_REF_NAME
    - ./gradlew -Pci --console=plain :app:testDebug

assembleRelease:
  stage: release
  script:
    - cd $CI_COMMIT_REF_NAME
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      # -Pandroid.injected.signing.key.password=$KEY_PASSWORD

    - cd ..
    # - mv ./$CI_COMMIT_REF_NAME/app/build/outputs/apk/release/app-release-unsigned.apk ./outputs/$CI_COMMIT_REF_NAME.apk
  artifacts:
    paths:
      # - ./
      - ./$CI_COMMIT_REF_NAME/app/build/outputs/apk/release/
    # - CHANGELOG
