image: jangrewe/gitlab-ci-android

variables:
  BUILD_APPS: "antitheftprotector calculator rollingdice todolistsimple"

before_script:
  - mkdir outputs


#   - export GRADLE_USER_HOME=$(pwd)/RollingDice/.gradle
#   - chmod +x ./RollingDice/gradlew

# cache:
#   key: ${CI_PROJECT_ID}
#   paths:
#     - .gradle/

stages:
  - build
  - test
  - release
  - deploy

# master #######################################################################
lintDebug:
  stage: build
  script:
    - >
      for APPNAME in $BUILD_APPS; do
        cd $APPNAME
        ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
        cd ..
      done
  only:
    refs:
      - master

assembleDebug:
  stage: build
  script:
    - >
      for APPNAME in $BUILD_APPS; do
        cd $APPNAME
        ./gradlew assembleDebug
        cd ..
      done
  only:
    refs:
      - master

testDebug:
  stage: test
  script:
    - >
      for APPNAME in $BUILD_APPS; do
        cd $APPNAME
        ./gradlew -Pci --console=plain :app:testDebug
        cd ..
      done
  only:
    refs:
      - master

assembleRelease:
  stage: release
  script:
    - >
      for APPNAME in $BUILD_APPS; do
        cd $APPNAME
        ./gradlew assembleRelease
        mv ./app/build/outputs/apk/release/app-release-unsigned.apk ../outputs/$APPNAME.apk
        cd ..
      done

  only:
    refs:
      - master
  artifacts:
    paths:
      - ./outputs
    # - CHANGELOG

    expire_in: 1 week
