image: jangrewe/gitlab-ci-android

before_script:
  - mkdir outputs
#   - export GRADLE_USER_HOME=$(pwd)/RollingDice/.gradle
#   - chmod +x ./RollingDice/gradlew

# cache:
#   key: ${CI_PROJECT_ID}
#   paths:
#     - .gradle/

stages:
  - build
  - test
  - release
  - deploy

# Calculator *****************************************************************/
lintDebugCalculator:
  stage: build
  script:
    - cd Calculator
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebugCalculator:
  stage: build
  script:
    - cd Calculator
    - ./gradlew assembleDebug

testDebugCalculator:
  stage: test
  script:
    - cd Calculator
    - ./gradlew -Pci --console=plain :app:testDebug

assembleReleaseCalculator:
  stage: release
  script:
    - cd Calculator
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      # -Pandroid.injected.signing.key.password=$KEY_PASSWORD

    - cd ..
    - mv ./Calculator/app/build/outputs/apk/release/app-release-unsigned.apk ./outputs/Calculator.apk
  artifacts:
    paths:
      - ./outputs
    # - CHANGELOG

# RollingDice *****************************************************************/
lintDebugRollingDice:
  stage: build
  script:
    - cd RollingDice
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebugRollingDice:
  stage: build
  script:
    - cd RollingDice
    - ./gradlew assembleDebug

testDebugRollingDice:
  stage: test
  script:
    - cd RollingDice
    - ./gradlew -Pci --console=plain :app:testDebug

assembleReleaseRollingDice:
  stage: release
  script:
    - cd RollingDice
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      # -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    - cd ..
    - mv ./RollingDice/app/build/outputs/apk/release/app-release-unsigned.apk ./outputs/RollingDice.apk
  artifacts:
    paths:
      - ./outputs
    # - CHANGELOG



# build:
#   stage: build
#   script:
#     - echo "Building"
#     - mkdir output
#     - cd RollingDice
#     - ./gradlew assemble
#     - cd ../output
#     - mv ../RollingDice/app/build/outputs/apk/debug/app-debug.apk ./RollingDice-debug.apk
#   artifacts:
#     paths:
#       - output/
#
# test:
#   stage: test
#   script:
#     - echo "Testing"
#     - test -f "output/RollingDice-debug.apk"
